export const AppNavConfig = [
	{
		id: 1,
		group_id: 0,
		sequence_no: 0,
		name: "Dashboard",
		controller: "/dashboard",
	},
	{
		id: 2,
		group_id: 0,
		sequence_no: 0,
		name: "Administration",
		submenu: [
			{
				id: 3,
				group_id: 2,
				sequence_no: 0,
				name: "Manage States",
				controller: "/administration/states",
			},
			{
				id: 4,
				group_id: 2,
				sequence_no: 0,
				name: "Manage Cities",
				controller: "/administration/cities",
			},
			{
				id: 5,
				group_id: 2,
				sequence_no: 0,
				name: "Manage Areas",
				controller: "/administration/areas",
			},
			{
				id: 6,
				group_id: 2,
				sequence_no: 0,
				name: "Manage Locations",
				controller: "/administration/locations",
			},
			{
				id: 7,
				group_id: 2,
				sequence_no: 0,
				name: "Manage Inquiry Area",
				controller: "/administration/inquiry-areas",
			},
			{
				id: 8,
				group_id: 2,
				sequence_no: 0,
				name: "Manage Premises",
				controller: "/administration/premises",
			},
			{
				id: 9,
				group_id: 2,
				sequence_no: 0,
				name: "Manage Premises Type",
				controller: "/administration/premises-types",
			},
			{
				id: 10,
				group_id: 2,
				sequence_no: 0,
				name: "Manage DSA",
				controller: "/administration/dsa",
			},
		],
	},
	{
		id: 11,
		group_id: 0,
		sequence_no: 0,
		name: "Inquiry",
		submenu: [
			{
				id: 12,
				group_id: 10,
				sequence_no: 0,
				name: "First Level 1",
				controller: "/first-level-1",
			},
			{
				id: 13,
				group_id: 10,
				sequence_no: 0,
				name: "First Level 2",
				controller: "/first-level-2",
			},
		],
	},
	{
		id: 14,
		group_id: 0,
		sequence_no: 0,
		name: "Wholesale Purchase",
		submenu: [
			{
				id: 15,
				group_id: 10,
				sequence_no: 0,
				name: "First Level 3",
				controller: "/first-level-3",
			},
			{
				id: 16,
				group_id: 10,
				sequence_no: 0,
				name: "First Level 4",
				controller: "/first-level-5",
			},
		],
	},
];
